
export const ADD_NOTE = 'ADD_NOTE'
export const LOGGED_IN_SUCCESSFULLY = 'LOGGED_IN_SUCCESSFULLY'
export const NOT_LOGGED_IN = 'NOT_LOGGED_IN'

export const RECEIVED_NOTES = 'RECEIVED_NOTES'
export const SUCCESSFUL_UPLOAD = 'SUCCESSFUL_UPLOAD'
export const FAILED_UPLOAD = 'FAILED_UPLOAD'
